### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by shu-paulsideleau** [shu-paulsideleau/shu-bowling#1]
# As a bowler, I want to register with bowling alley so that I can bowl without providing same information each and every time to lane attendant/bowling alley operator. [_71 hours_]

## Tasks

- [ ] Frontend : form design for registration **[5.5 hours]**

- [ ] Frontend : Add registration link to menu [**3 hours**]

- [ ] Frontend: client side validation logic for form data (age, email address, phone number, password)  [**3 hours**]

- [ ] Frontend:  implement REST service call to submit registration form data. [**5 hours**]

- [ ] Forntend: Implementation to handle failed scenario due to already registered user (by same phone number , same email address) [**4 hours**]

- [ ] Frontend: Implement Unit test cases for frontend implementation. [**7 hours**]

- [x] Backend:  Logic to validate the input form data (age, email address, phone number, password) [**3 hours**]

- [x] Backend: implement logic to check if user already registered. [**3 hours**]

- [x] Backend: Implementation to commit registration data to persistence storage (database) [**4 hours**]

- [x] Backend: Implementation to handle configuration for database connectivity (including handling username and password to connect to database ), email server connectivity [**3.5 hours**]

- [x] Backend: Implementation to wrap the backend code in REST service. [**5 hours**]

- [ ] Backend: Implementation to restrict REST service call from authorized client applications only [**4 hours**]

- [ ] Backend: Implementation to send activation email [**9 hours**]

- [ ] Backend: Implement REST service to activate bowler account [**3 hours**]

- [ ] Backend: Implement Unit test case for backend implementation. [**5 hours**]

- [x] Database: Database design for Bowler account [**3 hours**]

- [x] Database: Create database tables for Bowler  account details [**1 hours**]

## Acceptance Criteria
- Bowler should be able to register with following information

1. first name, last name, age
2. mailing address 
3. email address 
4. phone number 
5. password

- form should validate email address and phone number
- once user account is created, it should send mail to registered email address to activate the bowler account.
- Bowler account should be activated only when bowler confirm with activation link provided via email.
- Application service for registration should be accessible from authorized client applications only.

**Comment by togadiyaj** [comment]
# As a bowler, I want to register with bowling alley so that I can bowl without providing same information again and again to lane attendant/bowling alley operator.
- Bowler should be able to register with following information

1. first name, last name, age
2. mailing address 
3. email address 
4. phone number 
- form should validate email address and phone number
- Application service for registration should be accessible from authorized client applications only.
