### ISSUE TITLE
Shoes Inventory

### ISSUE THREAD

**Issue by MichaelMann358** [shu-paulsideleau/shu-bowling#11]
# As an employee, I need a way to see how many Bowling Shoes are available to rent out, of each size, so that I can better serve the customers. _[**44 hours**]_

## Task

- [ ] Frontend:  Form design that display the number of shoes available to rent out [**6 hours**]
- [ ] Frontend: REST service call to get number of shoes available. [**5 hours**]
- [ ] Frontend: Unit Test cases for frontend implementation. [**8 hours**]
- [ ] Backend: REST service implementation to get number of shoes [**12 hours**]
- [ ] Backend: Unit Test cases for backend implementation. [**7 hours**]
- [ ] Backend: Database Design for Shoes inventory [**4 hours**]
- [ ] Backend: Create tables for Shoes invenotry [**2 hours**]

## Acceptance Criteria

1. System should display following details for available shoes
     a. Shoes Size, number of shoes in use,
     b. number of shoes available,
     c.  total number of shoes in stock
