### ISSUE TITLE
Bowling Pins Inventory

### ISSUE THREAD

**Issue by togadiyaj** [shu-paulsideleau/shu-bowling#15]
# As an employee, I need to be able to keep track of our remaining inventory for Bowling Pins, so that they may be re-ordered if supplies are low.  [**35 hours**]

## Task

- [ ] Frontend:  Form design that display the pins inventory [**6 hours**]
- [ ] Frontend: REST service call to get pins inventory. [**4 hours**]
- [ ] Frontend: Unit Test cases for frontend implementation. [**5 hours**]
- [ ] Backend: REST service implementation to get pins inventory. [**10 hours**]
- [ ] Backend: Unit Test cases for backend implementation. [**6 hours**]
- [ ] Backend: Database Design for pins inventory [**3 hours**]
- [ ] Backend: Create tables for pins invenotory [**1 hours**]

## Acceptance Criteria

1. System should display following details
    a. Total number of pins available
    b. Total number of pins requires for alley to operate.
    c. Minimum number of pins requires in stock, so it can be replace damaged pins easily.
2. When number of pins in stock goes lower than minimum number of pins requires in stock, it should send notification to employee.
