### ISSUE TITLE
Bowling Balls Inventory

### ISSUE THREAD

**Issue by togadiyaj** [shu-paulsideleau/shu-bowling#16]
# As an employee, I need to be able to keep track of our stock Bowling Balls, replacing damaged goods as needed. [**31 hours**]

## Task

- [ ] Frontend:  Form design that display the  Bowling Balls inventory [**6 hours**]
- [ ] Frontend: REST service call to get  Bowling Balls inventory.  [**3 hours**]
- [ ] Frontend: Unit Test cases for frontend implementation. [**6 hours**]
- [ ] Backend: REST service implementation to get  Bowling Balls inventory.  [**6 hours**]
- [ ] Backend: Unit Test cases for backend implementation.  [**5 hours**]
- [ ] Backend: Database Design for  Bowling Balls inventory  [**3 hours**]
- [ ] Backend: Create tables for  Bowling Balls inventory  [**2 hours**]

## Acceptance Criteria

1. System should display following details
    a. Total number of  Bowling Balls available
    b. Total number of  Bowling Balls requires for alley to operate.
    c. Minimum number of  Bowling Balls requires in stock, so it can be replace damaged  Bowling Balls easily.
2. When number of  Bowling Balls in stock goes lower than minimum number of  Bowling Balls requires in stock, it should send notification to employee.
