### ISSUE TITLE
Score

### ISSUE THREAD

**Issue by patelmayank17** [shu-paulsideleau/shu-bowling#2]
# As a bowler, I want to know current team score after each throw [**_107 hours_**]

## Task

- [x] Frontend : Form design to display live score team wise [**7 hours**]
- [ ] Frontend : Form design to enter team player list for a game and start the game. [**5 hours**]
- [ ] Frontend: implement REST service call to trigger the game start. [**4 hours**]
- [ ] Frontend: Implement REST service call to simulate the throw and get the current score. [**5 hours**]
- [ ] Fronend:  Implement logic to update the score on screen. [**4 hours**]
- [ ] Frontend: Implement logic to highlight current user row in scoreboard  [**3 hours**]
- [ ] Frontend:  Implement logic to highlight the max score on scoreboard. [**3 hours**]
- [ ] Frontend: Implement logic to display greetings when someone score the strike or spares. [**4 hours**]
- [ ] Fronend: Implement Unit test cases for frontend implementation. [**9 hours**]
- [ ] Backend: Implementation to generate new score based on input from client. (follow rules provided in https://www.thoughtco.com/bowling-scoring-420895) [**15 hours**]
- [x] Backend: Implement REST service to start the game [**10 hours**]
- [ ] Backend: Implementation to store team details in database [**8 hours**]
- [ ] Backend: Implementation to store the current state of game in database. [**9 hours**]
- [ ] Backend: Implementation to restrict REST service call from authorized client applications only [**5 hours**]
- [ ] Backend: Implement Unit test case for backend implementation. [**8 hours**]
- [ ] Database: Database design for team details [**3 hours**]
- [ ] Database: Database design for game status [**3 hours**]
- [x] Database: Create database tables for team and game status. [**2 hours**]
 

## Acceptance Criteria
- At max only 10 player can play on single lane
- System should calculate score as explained at https://www.thoughtco.com/bowling-scoring-420895
- Application should provide option on screen to trigger the throw, for each throw, it should pickup random number of pins in range of 0-10.
- Screen should display updated score after each throw.
- Application service should take laneId and number Pins as input and calculate and return the current score of team.
**input format**
{
       laneId : 10,
       pins: 7
     }
**Output format:**
 {
  "player1": {
    "frames": [
      {
        "roll1": 10,
        "roll2": 10,
        "roll3": 10
      },
      {
        "roll1": 3,
        "roll2": 1
      },
      {
        "roll1": 10,
        "roll2": 9
      }
    ],
    "total": 38
  },
  "player2": {
    "frames": [
      {
        "roll1": 10,
        "roll2": 10
      },
      {
        "roll1": 2,
        "roll2": 1
      },
      {
        "roll1": 5,
        "roll2": 7
      }
    ],
    "total": 22
  }
}
- Application service for score should be accessible from authorized client applications only.

**Comment by togadiyaj** [comment]
# As a bowler, I want to know current team score after each throw

- System should calculate score as explained at https://www.thoughtco.com/bowling-scoring-420895
- Application service should take laneId and number Pins as input and calculate and return the current score of team.
**input format**
{
       laneId : 10,
       pins: 7
     }
**Output format:**
 {
  "player1": {
    "frames": [
      {
        "roll1": 10,
        "roll2": 10,
        "roll3": 10
      },
      {
        "roll1": 3,
        "roll2": 1
      },
      {
        "roll1": 10,
        "roll2": 9
      }
    ],
    "total": 38
  },
  "player2": {
    "frames": [
      {
        "roll1": 10,
        "roll2": 10
      },
      {
        "roll1": 2,
        "roll2": 1
      },
      {
        "roll1": 5,
        "roll2": 7
      }
    ],
    "total": 22
  }
}
- Application service for score should be accessible from authorized client applications only.
