### ISSUE TITLE
History

### ISSUE THREAD

**Issue by patelmayank17** [shu-paulsideleau/shu-bowling#3]
# As a registered bowler, I want to know my score history . [_**51 hours**_]

- System should display following details as part of score history
   1. Score by Frames (only for current user or for whole team ?)
   2. Lane Id  ?
   3. Date and Time ?
- Application service should take register user id as input and provide the score history as output.
- Application service should be accessible from authorized client applications only.

# **Tasks**
- [ ] #Frontend:  After authentication, a button should appear on the GUI to show score history. Input is unique player ID. Output is a list [date/time, last score, lane ID, game number (ordered from last game played)] [**12 hours**]
- [ ] #Backend: validate the unique player ID and session ID [**4 hours**]
- [ ] #Frontend: Implement logic to make a service call on a history button click. [**6 hours**]
- [ ] #Backend: REST service implementation to capture user request [**12 hours**]
- [ ] #Frontend: Implement logic to receive data from the REST service and display on the GUI [**5 hours**]
- [ ] #Backend: database service to query DB [**6 hours**]
- [ ] #Database: Design the database tables  [**4 hours**]
- [ ] #Database: Create the database tables  [**2 hours**]

# **Acceptance Criteria**

- An authenticated bowler should be able to click on a button named 'history' on the GUI after logging in to view their bowling history.
- The history should show all of their previous games including date/time, score, lane ID and game number.

**Comment by togadiyaj** [comment]
# As a registered bowler, I want to know my score history .

- System should display following details as part of score history
   1. Score by Frames (only for current user or for whole team ?)
   2. Lane Id  ?
   3. Date and Time ?
- Application service should take register user id as input and provide the score history as output.
- Application service should be accessible from authorized client applications only.

**Comment by robantonucci** [comment]
# **Tasks**
- [ ] #Frontend:  After authentication, a button should appear on the GUI to show score history. Input is unique player ID. Output is a list [date/time, last score, lane ID, game number (ordered from last game played)]
- [ ] #Backend: validate the unique player ID and session ID
- [ ] #Frontend: Implement logic to make a service call on a reserve alley button click.
- [ ] #Backend: REST service implementation to capture user request
- [ ] #Frontend: Implement logic to receive data from the REST service and display on the GUI
- [ ] #Backend: database service to query DB
- [ ] #Database: Design the database tables 
- [ ] #Database: Create the database tables 

# **Acceptance Criteria**

- An authenticated bowler should be able to click on a button named 'history' on the GUI after logging in to view their bowling history.
- The history should show all of their previous games including date/time, score, lane ID and game number.
