### ISSUE TITLE
Reserve Alley

### ISSUE THREAD

**Issue by robantonucci** [shu-paulsideleau/shu-bowling#5]
# As a bowler, I want to reserve an alley without having to talk to an employee first. [**_67 hours_**]

## Task

- [ ] #Frontend: Form design to reserve an alley which takes a number of players, date and time as input. [**10 hours**]
- [ ] #Frontend: To validate all input controls. [**5 hours**]
- [ ] #Fronend: Implement logic to make a service call on a reserve alley button click.  [**4 hours**]
- [ ] #Frontend: UT Test cases for frontend implementation [**8 hours**]
- [ ] #Frontend: Form to display the reservation confirmation and allow the user to print or email the same. [**8 hours**]
- [ ] #Backend: Implementation to get the client information if he/she is registered client and this information is used for reserving the alley. [**3 hours**]
- [ ] #Backend: REST service implementation to reserve an alley [**10 hours**]
- [ ] #Backend: Implementation to restrict REST service call from authorized client applications only. [**5 hours**]
- [ ] #Backend: UT Test cases for backend implementation [**7 hours**]
- [ ] #Database:  Design the database tables used in alley reservation [**5 hours**]
- [ ] #Database:  Create database tables used for alley reservation [**2 hours**]

# Acceptance Criteria

- An anonymous bowler and Authorized bowler should be able to reserve alley at any time.
- A bowler should be able to register with the following information:
       1. Number of Players
       2. Time
       3. Date
- A form should validate time and date.
- Once alley is reserved by the authorized user then the system sends automatically email to the user.
