### ISSUE TITLE
Number of Bowlers

### ISSUE THREAD

**Issue by ghost** [shu-paulsideleau/shu-bowling#7]
# As a bowler, I want to be able to configure the number of people bowling on my lane. _[**69 hours**]_

- bowler should be able to configure the team using lane number and name of each player. 
- At max, team size should be 6.
- Application service to configure the team should be accessible from authorized client applications only.

# **Tasks**
- [ ] #Frontend: Form design for anonymous bowler [**8 hours**]
- [ ] #Frontend: Form design for registered bowler [**2 hours**]
- [ ] #Fronend: Implement logic to make service call to backend. Input is **unique bowler ID, lane ID, number of bowlers (>0<7), team name** [**6 hours**]
- [ ] #Frontend: To validate all input controls. [**4 hours**]
- [ ]  #Backend: validate the unique player ID and session ID, number of bowlers. Check that number of bowlers is an integer, utlilize parameterized queries for team name to prevent injections [**10 hours**]
- [ ] #Frontend: UT Test cases for frontend implementation [**7 hours**]
- [ ] #Backend: REST service implementation [**12 hours**]
- [ ] #Backend: UT Test cases for backend implementation [**7 hours**]
- [ ]  #Frontend: Implement logic to receive data from the REST service and display on the GUI [**8 hours**]
- [ ] #Database: Design the database tables [**5 hours**]
- [ ] #Database: Create database tables [**2 hours**]

# **Acceptance Criteria**

- An anonymous user should be able to select how many people are on their team. No more than 6, no less than 1.
- A registered user should be able to select how many people are on their team. No more than 6, no less than 1. 

 ### REST Service Input format
{
  "laneId": 2,
  "bowlers": [
    {
      "name": "Player0"
    },
    {
      "name": "Player5"
    },
    {
      "name": "Player4"
    },
    {
      "name": "Player1"
    },
    {
      "name": "Player2"
    },
    {
      "name": "Player3"
    }
  ]
}

**Comment by togadiyaj** [comment]
-- bowler should be able to configure the team using lane number and name of each player. 
-- At least 2 member is required to enter the team details.
-- At max, team size should be 10.
-- Application service to configure the team should be accessible from authorized client applications only.
